title:              野马的博客
email:              xmpace@gmail.com
description:        野马的博客
author:             xmpace
baseurl:            ""
url:                "https://yemablog.com"

# Social Profiles
github_username:    xmpace
weibo_username:     5386697964
zhihu_username:     xmpace

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-146363058-1 # out your google-analytics code
baidu_tongji: 390b155f0f9a1f74e3b39b9b9238f3da

permalink: none
highlighter: rouge
collections:
  notes:
    output: true
    permalink: /:collection/:name

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/